"""initial schema with authentication and projects

Revision ID: 050d03fbb579
Revises: 
Create Date: 2026-01-05 07:59:28.589749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050d03fbb579'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('document_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('object_typology', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('custom_attributes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_images_filename'), 'document_images', ['filename'], unique=True)
    op.create_index(op.f('ix_document_images_id'), 'document_images', ['id'], unique=False)
    op.create_table('camera_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_image_id', sa.Integer(), nullable=False),
    sa.Column('camera_model', sa.String(length=255), nullable=True),
    sa.Column('camera_manufacturer', sa.String(length=255), nullable=True),
    sa.Column('lens_model', sa.String(length=255), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=50), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('exposure_compensation', sa.Float(), nullable=True),
    sa.Column('white_balance', sa.String(length=100), nullable=True),
    sa.Column('flash_used', sa.Boolean(), nullable=True),
    sa.Column('metering_mode', sa.String(length=100), nullable=True),
    sa.Column('focus_mode', sa.String(length=100), nullable=True),
    sa.Column('light_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_image_id'], ['document_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_image_id')
    )
    op.create_index(op.f('ix_camera_settings_id'), 'camera_settings', ['id'], unique=False)
    op.create_table('exif_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_image_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.Column('x_resolution', sa.Integer(), nullable=True),
    sa.Column('y_resolution', sa.Integer(), nullable=True),
    sa.Column('resolution_unit', sa.String(length=50), nullable=True),
    sa.Column('software', sa.String(length=255), nullable=True),
    sa.Column('datetime_original', sa.DateTime(), nullable=True),
    sa.Column('datetime_digitized', sa.DateTime(), nullable=True),
    sa.Column('thumbnail_data', sa.String(length=255), nullable=True),
    sa.Column('exposure_time', sa.String(length=50), nullable=True),
    sa.Column('f_number', sa.String(length=50), nullable=True),
    sa.Column('iso_speed_ratings', sa.Integer(), nullable=True),
    sa.Column('focal_length', sa.String(length=50), nullable=True),
    sa.Column('focal_length_in_35mm', sa.Integer(), nullable=True),
    sa.Column('lens_model', sa.String(length=255), nullable=True),
    sa.Column('flash', sa.String(length=100), nullable=True),
    sa.Column('white_balance', sa.String(length=100), nullable=True),
    sa.Column('exposure_compensation', sa.String(length=50), nullable=True),
    sa.Column('metering_mode', sa.String(length=100), nullable=True),
    sa.Column('light_source', sa.String(length=100), nullable=True),
    sa.Column('color_space', sa.String(length=100), nullable=True),
    sa.Column('gps_latitude', sa.String(length=100), nullable=True),
    sa.Column('gps_longitude', sa.String(length=100), nullable=True),
    sa.Column('gps_altitude', sa.String(length=100), nullable=True),
    sa.Column('gps_timestamp', sa.DateTime(), nullable=True),
    sa.Column('raw_exif', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_image_id'], ['document_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exif_data_id'), 'exif_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exif_data_id'), table_name='exif_data')
    op.drop_table('exif_data')
    op.drop_index(op.f('ix_camera_settings_id'), table_name='camera_settings')
    op.drop_table('camera_settings')
    op.drop_index(op.f('ix_document_images_id'), table_name='document_images')
    op.drop_index(op.f('ix_document_images_filename'), table_name='document_images')
    op.drop_table('document_images')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
