"""add user authentication and project management

Revision ID: 1081dffa60ff
Revises: 6e3fcdc6116d
Create Date: 2026-01-05 07:53:16.450958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1081dffa60ff'
down_revision: Union[str, None] = '6e3fcdc6116d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
