"""refactor: separate Record from RecordImage models

Revision ID: 19e2aefe5b17
Revises: 48189f9482e3
Create Date: 2026-02-16 22:01:11.720584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19e2aefe5b17'
down_revision: Union[str, None] = '48189f9482e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create the new records table
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_typology', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('custom_attributes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('NOT (project_id IS NOT NULL AND collection_id IS NOT NULL)', name='check_record_single_parent'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    
    # Step 2: Add new columns to record_images (nullable first for data migration)
    op.add_column('record_images', sa.Column('record_id', sa.Integer(), nullable=True))
    op.add_column('record_images', sa.Column('capture_id', sa.String(length=36), nullable=True))
    op.add_column('record_images', sa.Column('pair_id', sa.String(length=36), nullable=True))
    op.add_column('record_images', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('record_images', sa.Column('role', sa.String(length=50), nullable=True))
    
    # Step 3: Migrate existing data - create one Record per RecordImage
    # This preserves all existing descriptive metadata
    connection = op.get_bind()
    
    # Get all existing record_images
    result = connection.execute(sa.text("""
        SELECT id, title, description, object_typology, author, material, date, 
               custom_attributes, project_id, collection_id, created_at, uploaded_by
        FROM record_images
    """))
    
    for row in result:
        # Create a Record from each RecordImage's descriptive metadata
        record_title = row.title or f"Untitled Record {row.id}"
        
        connection.execute(sa.text("""
            INSERT INTO records (title, description, object_typology, author, material, date,
                                custom_attributes, project_id, collection_id, created_at, created_by)
            VALUES (:title, :description, :object_typology, :author, :material, :date,
                    :custom_attributes, :project_id, :collection_id, :created_at, :created_by)
        """), {
            'title': record_title,
            'description': row.description,
            'object_typology': row.object_typology,
            'author': row.author,
            'material': row.material,
            'date': row.date,
            'custom_attributes': row.custom_attributes,
            'project_id': row.project_id,
            'collection_id': row.collection_id,
            'created_at': row.created_at,
            'created_by': row.uploaded_by
        })
        
        # Get the ID of the just-created record
        new_record_id_result = connection.execute(sa.text("SELECT lastval()"))
        new_record_id = new_record_id_result.scalar()
        
        # Link the RecordImage to the new Record
        connection.execute(sa.text("""
            UPDATE record_images SET record_id = :record_id WHERE id = :image_id
        """), {'record_id': new_record_id, 'image_id': row.id})
    
    # Step 4: Now make record_id NOT NULL (all rows should have values now)
    op.alter_column('record_images', 'record_id', nullable=False)
    
    # Step 5: Update indexes and constraints
    op.drop_index(op.f('ix_record_images_filename'), table_name='record_images')
    op.create_index(op.f('ix_record_images_filename'), 'record_images', ['filename'], unique=False)
    op.create_index(op.f('ix_record_images_capture_id'), 'record_images', ['capture_id'], unique=False)
    op.create_index(op.f('ix_record_images_pair_id'), 'record_images', ['pair_id'], unique=False)
    op.create_index(op.f('ix_record_images_record_id'), 'record_images', ['record_id'], unique=False)
    op.drop_constraint('record_images_collection_id_fkey', 'record_images', type_='foreignkey')
    op.drop_constraint('record_images_project_id_fkey', 'record_images', type_='foreignkey')
    op.create_foreign_key(None, 'record_images', 'records', ['record_id'], ['id'], ondelete='CASCADE')
    
    # Step 6: Drop old columns from record_images
    op.drop_column('record_images', 'modified_at')
    op.drop_column('record_images', 'material')
    op.drop_column('record_images', 'collection_id')
    op.drop_column('record_images', 'project_id')
    op.drop_column('record_images', 'custom_attributes')
    op.drop_column('record_images', 'description')
    op.drop_column('record_images', 'object_typology')
    op.drop_column('record_images', 'title')
    op.drop_column('record_images', 'author')
    op.drop_column('record_images', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_images', sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('object_typology', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('custom_attributes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('material', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('record_images', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record_images', type_='foreignkey')
    op.create_foreign_key(op.f('record_images_project_id_fkey'), 'record_images', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('record_images_collection_id_fkey'), 'record_images', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_record_images_record_id'), table_name='record_images')
    op.drop_index(op.f('ix_record_images_pair_id'), table_name='record_images')
    op.drop_index(op.f('ix_record_images_capture_id'), table_name='record_images')
    op.drop_index(op.f('ix_record_images_filename'), table_name='record_images')
    op.create_index(op.f('ix_record_images_filename'), 'record_images', ['filename'], unique=True)
    op.drop_column('record_images', 'role')
    op.drop_column('record_images', 'sequence')
    op.drop_column('record_images', 'pair_id')
    op.drop_column('record_images', 'capture_id')
    op.drop_column('record_images', 'record_id')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
