"""add collections table and update records with collection_id

Revision ID: 48189f9482e3
Revises: c3d4e5f6a7b8
Create Date: 2026-02-16 20:22:02.487411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48189f9482e3'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_type', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('parent_collection_id', sa.Integer(), nullable=True),
    sa.Column('archival_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(project_id IS NOT NULL AND parent_collection_id IS NULL) OR (project_id IS NULL AND parent_collection_id IS NOT NULL)', name='check_collection_parent'),
    sa.ForeignKeyConstraint(['parent_collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.add_column('record_images', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('document_images_project_id_fkey'), 'record_images', type_='foreignkey')
    op.create_foreign_key(None, 'record_images', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'record_images', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('check_record_single_parent', 'record_images', 'NOT (project_id IS NOT NULL AND collection_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_record_single_parent', 'record_images', type_='check')
    op.drop_constraint(None, 'record_images', type_='foreignkey')
    op.drop_constraint(None, 'record_images', type_='foreignkey')
    op.create_foreign_key(op.f('document_images_project_id_fkey'), 'record_images', 'projects', ['project_id'], ['id'])
    op.drop_column('record_images', 'collection_id')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
