"""add fondo serie signatura to projects

Revision ID: 5452647b9eae
Revises: 2dfe4c99b732
Create Date: 2026-05-23 12:57:16.595161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5452647b9eae'
down_revision: Union[str, None] = '2dfe4c99b732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fondo', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('serie', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('signatura', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'signatura')
    op.drop_column('projects', 'serie')
    op.drop_column('projects', 'fondo')
    # ### end Alembic commands ###
