"""add_status_sequence_to_records

Revision ID: 5e9345333809
Revises: c53499083576
Create Date: 2026-05-24 19:43:58.850520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5e9345333809'
down_revision: Union[str, None] = 'c53499083576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('status', sa.String(length=20), nullable=False, server_default='captured'))
    op.add_column('records', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('records', sa.Column('rejection_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'rejection_note')
    op.drop_column('records', 'sequence')
    op.drop_column('records', 'status')
    # ### end Alembic commands ###
