"""add export version tracking to collections

Revision ID: dda9bc1bc608
Revises: 5e9345333809
Create Date: 2026-05-24 21:14:12.394780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dda9bc1bc608'
down_revision: Union[str, None] = '5e9345333809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.add_column('collections', sa.Column('export_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('collections', sa.Column('last_exported_at', sa.DateTime(), nullable=True))
    op.add_column('collections', sa.Column('last_export_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'last_export_hash')
    op.drop_column('collections', 'last_exported_at')
    op.drop_column('collections', 'export_version')
    op.create_table('project_members',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_members_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('project_members_pkey'))
    )
    # ### end Alembic commands ###
